development:
  base_url: 'https://example-dev.library.columbia.edu/api'
  username: 'example-user'
  password: 'example-password'
  timeout: 60

test:
  base_url: 'https://example-test.library.columbia.edu/api'
  username: 'example-user'
  password: 'example-password'
  timeout: 20