development:
  instance1:
    base_url: 'https://example1-dev.library.edu/api'
    username: 'example-user'
    password: 'example-password'
    timeout: 60

  instance2:
    base_url: 'https://example2-dev.library.edu/api'
    username: 'example-user'
    password: 'example-password'
    timeout: 60

test:
  instance1:
    base_url: 'https://example1-test.library.edu/api'
    username: 'example-user'
    password: 'example-password'
    timeout: 60

  instance2:
    base_url: 'https://example2-test.library.edu/api'
    username: 'example-user'
    password: 'example-password'
    timeout: 60