shared: &shared
  default_sender_email_address: test@example.com

development:
  <<: *shared
  marc_sync_email_addresses:
    - test1@example.com
    - test2@example.com

test:
  <<: *shared
  marc_sync_email_addresses:
    - test1@example.com
    - test2@example.com