development:
  default_sender_email_address: folio-sync@abc.com

  aspace_to_folio:
    # NOTE: MARC files will actually be downloaded to "#{marc_download_base_directory}/#{instance_key}"
    marc_download_base_directory: <%= Rails.root.join('tmp/development/downloaded_files') %>
    developer_email_address: developer_email@example.com

    aspace_instances:
      instance1:
        marc_sync_email_addresses:
          - user1@example.com

      instance2:
        marc_sync_email_addresses:
          - user2@example.com
          - user3@example.com

test:
  default_sender_email_address: folio-sync@abc.com

  aspace_to_folio:
    # NOTE: MARC files will actually be downloaded to "#{marc_download_base_directory}/#{instance_key}"
    marc_download_base_directory: <%= Rails.root.join('tmp/test/downloaded_files') %>
    developer_email_address: developer_email@example.com

    aspace_instances:
      instance1:
        marc_sync_email_addresses:
          - user1@example.com

      instance2:
        marc_sync_email_addresses:
          - user2@example.com
          - user3@example.com