development:
  base_url: https://example-dev.folio.com/api
  username: example-user
  password: example-password
  tenant: example-tenant
  timeout: 60

production:
  base_url: https://example-prod.folio.com/api
  username: example-user
  password: example-password
  tenant: example-tenant
  timeout: 60

test:
  base_url: https://example-test.folio.com/api
  username: example-user
  password: example-password
  tenant: example-tenant
  timeout: 60