development:
  location_codes:
    library1: library1-folio-location-code
    library2: library2-folio-location-code

  holdings_type_id: folio-holdings-type-uuid
  holdings_source_id: folio-holdings-source-uuid
  holdings_call_number_type_id: folio-holdings-call-number-type-uuid